work_dir: /data1/gty/2022_work_dir/AimCLR_v2_3views/ntu60_cv/top-4-20/linear_eval_400

weights: /data1/gty/2022_work_dir/AimCLR_v2_3views/ntu60_cv/top-4-20/pretext/epoch400_model.pt
ignore_weights: [encoder_q.fc, encoder_q_motion.fc, encoder_q_bone.fc, encoder_k, encoder_k_motion, encoder_k_bone, queue, queue_motion, queue_bone]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /data1/gty/action_dataset/ntu60_frame50/xview/train_position.npy
  label_path: /data1/gty/action_dataset/ntu60_frame50/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /data1/gty/action_dataset/ntu60_frame50/xview/val_position.npy
  label_path: /data1/gty/action_dataset/ntu60_frame50/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr_v2_3views.AimCLR_v2_3views
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [4]
batch_size: 128
test_batch_size: 128
num_epoch: 100
stream: 'all'

# log
save_interval: -1
eval_interval: 5
